# Generated by Django 5.0.4 on 2024-05-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=255, verbose_name='От пользователя')),
                ('to_user', models.CharField(max_length=255, verbose_name='К пользователя')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Перевод завершен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма перевода')),
            ],
            options={
                'verbose_name': 'История перевода',
                'verbose_name_plural': 'История переводов',
            },
        ),
    ]
