# Generated by Django 5.0.4 on 2024-05-09 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historytransfer',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_user', to=settings.AUTH_USER_MODEL, to_field='wallet_address', verbose_name='От пользователя'),
        ),
        migrations.AlterField(
            model_name='historytransfer',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='got_user', to=settings.AUTH_USER_MODEL, to_field='wallet_address', verbose_name='От пользователя'),
        ),
    ]
